### ISSUE TITLE
Editor component does not restart/rerender on prop 'id' change

### ISSUE THREAD

**Issue by Rugshtyne** [ckeditor/ckeditor5-react#234] opened 2021-04-15 13:53 UTC
If you externally provide the 'id' prop to CKEditor React component and then try to change it (using a button, for example), the component does not rerender/restart. This is needed, for example, for language change.

Looking at the source code it appears that in `shouldComponentUpdate(nextProps)` the prop change check should indicate update but in the end what is seen that the whole HTML of the component disappears. As if only `this._destroyEditor()` gets called and not `this._initializeEditor()`.

For example, before the id change the DOM structure looks like this:
![image](https://user-images.githubusercontent.com/36242162/114880448-bf395800-9e0a-11eb-90f9-7d2f465974b9.png)
and after:
![image](https://user-images.githubusercontent.com/36242162/114880554-d11afb00-9e0a-11eb-9247-81d0c0dce8ba.png)
(only inner content left)

I assume this is a bug, otherwise you should provide a how-to regarding CKEditor component rerenders/restarts.

**Comment by pomek** [comment] 2021-04-15 14:01
cc: @ma2ciek

**Comment by ma2ciek** [comment] 2021-04-15 16:22
I'm wondering if this might be a race condition issue occurring from time to time during the editor recreation.

**Comment by Rugshtyne** [comment] 2021-04-19 13:01
@ma2ciek just to make sure, if we, say, change a language in config and then want to rerender the CKEditor (so the changes would reflect), should we just trigger the prop "id" change? Or are we doing something wrong here? As far as I understand that is the only option currently to trigger the rerender.

**Comment by ma2ciek** [comment] 2021-10-07 08:17
I'm marking it as a bug, but AFAIR we could not reproduce this issue. However, it seems that this can be valid in some circumstances.

**Comment by Rugshtyne** [comment] 2021-10-13 08:32
@ma2ciek could you then provide the steps how did you try to reproduce it? Might be a correct way how to trigger rerender of the CKEditor then. :)

**Comment by pomek** [comment] 2023-03-08 08:19
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Devops-team-61725eed3bef5e001b521a89/issues/ckeditor/ckeditor5-react/234?planning-poker) with Zenhub @przemyslaw-zan @psmyrek

**Comment by martnpaneq** [comment] 2023-03-24 10:46
Looks like this bug was fixed along with some other bugs about half a year ago.
This is how it looks now:
![ezgif com-optimize](https://user-images.githubusercontent.com/114912428/227500849-ac22119d-b007-42f9-b510-055495a5c793.gif)

**Comment by pomek** [comment] 2023-03-27 11:48
Good. So, let's close it as resolved.

**Closed by pomek** 2023-03-27 11:48 UTC
Labels: type:bug, squad:devops, status:in-progress
