### ISSUE TITLE
Custom Template cannot be applied to the comments. 

### ISSUE THREAD

**Issue by mustafahlvc** [ckeditor/ckeditor5-react#211] opened 2021-01-19 10:59 UTC
Hi, 

I'm trying to apply custom template to the comments like the example at: https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/annotation-customization/annotations-custom-template.html#live-demo

I'm using custom build  which is generated with the [online builder](https://ckeditor.com/ckeditor-5/online-builder/).

I needed to import "@ckeditor/ckeditor5-comments" and "@ckeditor/ckeditor5-ui"

And i m getting **2 types of errors**:

1. I'm using create-react-app and the it's not allowing import from node_modules package

```
./node_modules/@ckeditor/ckeditor5-collaboration-core/theme/users.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@ckeditor/ckeditor5-collaboration-core/theme/users.css)
Module not found: Can't resolve './@ckeditor/ckeditor5-ui/theme/mixins/_unselectable.css' in '/home/www/IcarusUI/node_modules/@ckeditor/ckeditor5-collaboration-core/theme'
``` 
I hard coded this line inside at _node_modules/@ckeditor/ckeditor5-collaboration-core/theme/users.css_
`@import '@ckeditor/ckeditor5-ui/theme/mixins/_unselectable.css';`
to
`@import '../../ckeditor5-ui/theme/mixins/_unselectable.css'; `

for to resolve temporarily and getting the next error:

2. I assume this appears because I'm using customized build.
```
CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules
```

Is there any custom template/view example works with custom build with using create-react-app as generator?

**Comment by mustafahlvc** [comment] 2021-01-22 09:49
I have created a repository to demonstrate issue at https://github.com/mustafahlvc/cra-ckeditor-issue.


Please could you give ma a way to use custom templating feature.

**Comment by FilipTokarski** [comment] 2021-01-25 09:41
Hi, thanks for the report. The repo you linked looks like an empty React app, so I'm not sure what should I do with it. Please share some working demo that reproduces the error, so we could look into this. Also please make sure to followe the [integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) ( and the part about [online builder](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-a-build-from-the-online-builder) ).  
Now as it comes to comments - as it is a premium feature, we highly encourage you to use our dedicated [support channel](https://ckeditor.com/contact/). Our support team will investigate the problem and get back to you as soon as possible.

**Comment by mustafahlvc** [comment] 2021-01-27 10:55
Sorry @FilipTokarski  i ve pushed the commit and already opened a ticket from support channel.

**Comment by FilipTokarski** [comment] 2021-01-27 11:22
Can we close this ticket then?

**Comment by mustafahlvc** [comment] 2021-01-27 12:31
I can't get support from the ticket system and still i can't manage to customize comment view in the create-react-app project via looking documentation.

So please do not close.

**Comment by lslowikowska** [comment] 2021-01-27 15:10
Hi @mustafahlvc, thank you for reaching out to us again. I have just sent you an email - please check it and let's continue the discussion there.

**Closed** 2021-01-27 15:12 UTC
Labels: pending:feedback, type:question
