### ISSUE TITLE
Error - The requested plugin is not loaded. (plugincollection-plugin-not-loaded)

### ISSUE THREAD

**Issue by Anuj-logiciel** [ckeditor/ckeditor5-react#155] opened 2020-06-02 07:10 UTC
Getting Error when trying to add plugin with Editor. I am trying to use Mention plugin with Editor. 

Taking Code Ref. from - https://ckeditor.com/docs/ckeditor5/latest/examples/framework/chat-with-mentions.html#source-code

Error - `CKEditorError: plugincollection-plugin-not-loaded: The requested plugin is not loaded.`

![image](https://user-images.githubusercontent.com/22930446/83490314-736d1100-a4cd-11ea-9a53-59835540bc8e.png)

Also tried by doing like - `ClassicEditor.builtinPlugins = [Mention];` and the creating instance of plugin.

While searching for fix, I seen - [Same issue with Vue CKEditor](https://github.com/ckeditor/ckeditor5-vue/issues/69) . But I've no idea how to fix it with react.

Any quick help would be appreciated. Thanks in advance!!

**Comment by FilipTokarski** [comment] 2020-06-02 09:16
Hi, thanks for the report. I checked it and mention plugin works fine for me. If you want to integrate CKEditor with React, first make sure that you [follow our integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html). Especially if you want to add plugins, please read about [customising builds in React](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#customizing-the-builds) and [integrating app from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source).
Now, it's hard for me to guess what's going on without seeing your app configuration, so please provide it together with step-by-step description what you did, so I can  reproduce this issue.

**Comment by Anuj-logiciel** [comment] 2020-06-02 10:39
Hi @FilipTokarski , I've followed same and did same till - 

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-ckeditor-5-source

Yet I am getting issue. Also if I remove plugin, It doesn't let me type... Any Idea?

**Comment by FilipTokarski** [comment] 2020-06-02 10:44
Could you paste here contents of your `package.json` and editor component file?

**Comment by Anuj-logiciel** [comment] 2020-06-02 11:52
After investigating a little. I can find that - Using ClassicEditor by 2 different ways giving different behaviours - 

Here's same code which I used from example code of plugin.

```
import React, { Component } from 'react';
import CKEditor from '@ckeditor/ckeditor5-react';

// import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

import Mention from '@ckeditor/ckeditor5-mention/src/mention';

class Editor extends Component {
    render() {
        return (
		<CKEditor
			editor={ ClassicEditor }
			config={ {
				plugins: [ Mention ],
			} }
			data="<p>Hello from CKEditor 5!</p>"
			onInit={ editor => {
				// You can store the "editor" and use when it is needed.
				console.log( 'Editor is ready to use!', editor );
			} }
			onChange={ ( event, editor ) => {
				const data = editor.getData();
				console.log( { event, editor, data } );
			} }
			onBlur={ ( event, editor ) => {
				console.log( 'Blur.', editor );
			} }
			onFocus={ ( event, editor ) => {
				console.log( 'Focus.', editor );
			} }
		/>
		)
    }
}
```
Note: Respective imported packages have been installed in package file...

If I use `ClassicEditor` from 
`import ClassicEditor from '@ckeditor/ckeditor5-build-classic';` - it works fine. (But it starts giving Error - `CKEditorError: ckeditor-duplicated-modules`) error when used any plugin with this, so I want to use below one.

![image](https://user-images.githubusercontent.com/22930446/83516116-23557500-a4f4-11ea-97f8-524262858fd2.png)

`import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor'` - It doesn't let me input anything.
![image](https://user-images.githubusercontent.com/22930446/83515935-c8bc1900-a4f3-11ea-8b15-9473b7fabf45.png)

**Comment by FilipTokarski** [comment] 2020-06-02 12:18
Yes, that's why I linked the docs in my previous comment. If you use `@ckeditor/ckeditor5-build-classic` and add a plugin, you will always get `duplicated-modules error` - you cannot modify an already built editor. If you want to customise the editor by adding plugins there are two ways:
- [building editor from source in React](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source)
- [creating a standalone editor build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) and [adding it to React app](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#quick-start) ( in this example import your editor instead of `@ckeditor/ckeditor5-build-classic` )

Now as it comes to the second problem, it's caused by not passing proper configuration to `CKEditor` component. Please compare and see the comments in the code below ( it's an example of Inline editor built from source in React ):
```js
import React, { Component } from 'react';

import CKEditor from '@ckeditor/ckeditor5-react';

// Install and import the editor and plugins that you want
import InlineEditor from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Mention from '@ckeditor/ckeditor5-mention/src/mention';
import Link from '@ckeditor/ckeditor5-link/src/link';

// Create a configuration object
const editorConfiguration = {
    plugins: [ Essentials, Bold, Italic, Paragraph, Mention, Link  ],
    toolbar: [ 'bold', 'italic', 'link' ]
    // ..and all other options that you need, for example Mention
};

class App extends Component {
    render() {
        return (
            <div className="App">
                <h2>Using CKEditor 5 from source in React</h2>
                <CKEditor
                    editor={ InlineEditor }
                    // pass the configuration object below
                    config={ editorConfiguration }
                    data="<p>Hello from CKEditor 5!</p>"
                    onInit={ editor => {
                        // You can store the "editor" and use when it is needed.
                        console.log( 'Editor is ready to use!', editor );
                    } }
                />
            </div>
        );
    }
}

export default App;
```

I hope that helps!

**Comment by Anuj-logiciel** [comment] 2020-06-02 21:22
Thanks a lot @FilipTokarski . Your suggestions provided a big help to me to get out of the problem.

**Comment by FilipTokarski** [comment] 2020-06-03 06:25
I'm happy to hear that 🙂  So I'll close this ticket for now.

**Closed by FilipTokarski** 2020-06-03 06:25 UTC
Labels: pending:feedback, type:question

**Comment by shalapatil** [comment] 2023-05-09 14:24
Hello, 
I was facing similar problem for generalHTMLSupport and sourceEditing plugin
But when I add these two in plugins, I get `Cannot read properties of undefined (reading 'generalHTMLSupport')` 

I am using custom ckeditor5 with react. 

config is defined as 
`const CKEDITOR_BASE_CONFIG_FOR_PRESETS = {
 plugins: [
 window.CKEditor5.autoformat.Autoformat,
  window.CKEditor5.basicStyles.Bold,
  ..........
 window.Ckeditor5.generalHTMLSupport.GeneralHTMLSupport,`],
toolbar: {.....}`

Any help will be really appreciated. 
Thanks
