### ISSUE TITLE
Editor not displaying at first load with Strictmode

### ISSUE THREAD

**Issue by EmrickPesce** [ckeditor/ckeditor5-react#338] opened 2022-10-25 07:36 UTC
Hello team !

Thank you for your hard work :)

I noticed that my editor wasn't displayed when I start my server (with npm start). To make it showing, I need to reload the page on my navigator, and then it's working fine.

After multiple hours of research I found out that it was occurring because of the React StrictMode. This also comes because I retrieve some data from my own server, and I use _useEffect_ for waiting that all data is loaded before displaying anything.

You can reproduce it in a new React App, with just this code:

```jsx
// App.js:
import React, { useEffect, useState } from "react";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import { CKEditor } from "@ckeditor/ckeditor5-react";

function App() {
  const [isLoading, setIsLoading] = useState(true);
  var someData = "notEmpty";

  useEffect(() => {
    setTimeout(function () {
      someData && setIsLoading(false);
    }, 1000); // Simulate some data loading from a server
  }, [someData]);

  return (
    <>
      {isLoading ? (
        <i>Logo loading</i>
      ) : (
        <>
          <div className="App">
            <CKEditor
              editor={ClassicEditor}
              data="<p>Hello from CKEditor 5!</p>"
            />
          </div>
        </>
      )}
    </>
  );
}

export default App;
```

```jsx
// index.js:
`import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

Hope you can reproduce it. If you have any questions, do not hesitate;

Thank you for all !

**Comment by corymharper** [comment] 2022-10-28 17:52
I stuck this in a sandbox for convenience: https://codesandbox.io/s/ecstatic-lamarr-85bjw8?file=/src/index.js

You can reproduce the issue by opening the sandbox website in a new tab, any initial load will display the error, but for some reason refreshes won't. The fact that its happening only in strict mode and didn't happen before React 18 probably means it has something to do with the new double invocation behavior described here: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects, it also means it does not happen in development mode, more than likely.

**Comment by corymharper** [comment] 2022-11-08 19:03
Some more information I've discovered: 

On the renders the the editor does not initialize, a new `componentDidMount` lifecycle method is being called before the completion of `componentWillUnmount` from the previous cycle has been run to completion. Specifically `_destroyEditor` is called, and starts to run, but when the call to `this.watchdog.destroy` occurs in that method, a new call to `componentDidMount` has already been registered. It calls `_initializeEditor`, however the line in `_destroyEditor` that unsets the watchdog has not been run yet at this point ([this.watchdog = null](https://github.com/ckeditor/ckeditor5-react/blob/master/src/ckeditor.jsx#L229)). Such that when [this check](https://github.com/ckeditor/ckeditor5-react/blob/master/src/ckeditor.jsx#L139) occurs, there is a value assigned to it, and no new editor is initialized. Afterwards the function that destroys the editor runs to completion and destroys the editor with no initialization afterwards.

**Comment by corymharper** [comment] 2022-11-09 20:32
When the component fails to render properly, this is what the lifecycle looks like (confirmed via logging):

```
> Component mounted
> Editor created
> Component will unmount
> Watchdog destruction begins
> Component mounted
> Watchdog already present, no new watchdog or editor initialized
> Watchdog destruction completed
> Watchdog unset after destroy
```

As you can see from those logs, the editor finishes being created, an unmount happens, the process of destroying the watchdog and later the editor begins, `componentDidMount` fires with `_initializeEditor`, but `this.watchdog` is still present, so it skips initializing another watchdog/editor. Subsequently, the destruction process is completed, so you are left with no watchdog/editor.

**Comment by corymharper** [comment] 2022-11-09 20:37
I am currently fixing this locally by forcing the `_initializeEditor` to wait for any pending destruction. Here's a summary of my implementation:

```js
// In the constructor:
export default class CKEditor extends React.Component {
	constructor( props ) {
		super( props );

		this.destructionInProgress = null;
...
```

```js
// _initializeEditor():
	async _initializeEditor() {
		if ( this.destructionInProgress ) {
			await this.destructionInProgress;
		}
```

```js
// componentWillUnmount():
	async componentWillUnmount() {
		this.destructionInProgress = new Promise( resolve => {
			this._destroyEditor().then( () => {
				resolve();
			} );
		} ).then( () => {
			this.destructionInProgress = null;
		} );
	}
```

**Comment by pomek** [comment] 2022-11-10 07:42
Hi @corymharper, thanks for the detailed comments you have written. They explain the problem a bit. We'd appreciate it if you could prepare a PR with these changes.

**Comment by corymharper** [comment] 2022-11-10 20:23
@pomek at your convenience, #342 is ready for review.

**Closed** 2022-11-23 09:19 UTC
Labels: squad:devops, status:in-progress
