### ISSUE TITLE
CkEditor loads but has no UI

### ISSUE THREAD

**Issue by b-rahmani** [ckeditor/ckeditor5-react#362] opened 2023-02-19 08:03 UTC
I'm trying to incorporate CkEditor 5 into my complex React + Vite application.

It loads but it does not show its UI.

Here's the [MRE repo](https://github.com/b-rahmani/CkEditorLoadsWithoutUi). Please follow these steps to reproduce:

1. Clone the repo
2. `npm install`
3. `npm run dev`
4. Switch between **Dashboard** and **Post HTML** in the menu
5. See the console
6. You should see that it says CkEditor is ready, but you should see no UI

And the code for CkEditor is in:

```
/src/Components/Form/Fields/HtmlRte.jsx
/src/Components/Form/Fields/RteConfig.jsx
```

I would really appreciate your help. Thank you.

**Comment by Reinmar** [comment] 2023-04-11 06:49
Sorry for the very late reply, but for the people who will see this issue in the future:

*   [https://github.com/ckeditor/vite-plugin-ckeditor5](https://github.com/ckeditor/vite-plugin-ckeditor5)
*   https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source-vite.html

**Comment by Reinmar** [comment] 2023-04-11 06:50
I think the issue is resolved by our custom plugin for Vite, so I'm closing this.

**Closed by Reinmar** 2023-04-11 06:50 UTC
