### ISSUE TITLE
Templates 

### ISSUE THREAD

**Issue by rffensick** [ckeditor/ckeditor5-react#70] opened 2019-02-28 07:56 UTC
How to add Content Templates in ckeditor 5?

**Comment by Mgsy** [comment] 2019-02-28 08:08
>How to add Content Templates in ckeditor 5?

Hi, could you tell us more about your question? What do you mean by `content templates` and what is your use case? Is your question related to the CKEditor 5 React integration?

**Comment by rffensick** [comment] 2019-02-28 08:24
@Mgsy Yes, I want add custom templates in React editor like in ckEditor 4 - like this: 
```javascript
CKEDITOR.editorConfig = function( config ) {
    config.templates_files = ['/js/ckeditor/templates/default.js'];
    config.templates = 'default';
    config.allowedContent = true;
    config.templates_replaceContent = true;
};
```

**Comment by Mgsy** [comment] 2019-02-28 08:50
CKEditor 5 doesn't support templates as CKEditor 4, so there is no possibility to define them. Your question isn't related to the React integration, so I'm closing this issue. 

I saw you've opened an issue in the main [CKEditor 5 repository](https://github.com/ckeditor/ckeditor5/issues/1585). It was closed because the description indicated that the problem is related to CKEditor 4, but I'll re-open it as a feature request.

**Closed by Mgsy** 2019-02-28 08:50 UTC
Labels: type:feature
