### ISSUE TITLE
Extra char inputed when input Chinese character on Safari (15.5) on macOS 12.4

### ISSUE THREAD

**Issue by smoothdvd** [ckeditor/ckeditor5-react#311] opened 2022-05-19 05:16 UTC
https://user-images.githubusercontent.com/22420/169213112-0c1e38a7-6a35-42c4-a71e-3521a842f2ef.mov

In video, you can see there is a extra 's' inputed early when input Chinese character '要'(In Chinese 'Wubi' input method, you type 's' key to input '要' character). 

On Chrome browser it works no problem.

**Comment by FilipTokarski** [comment] 2022-05-23 08:48
Thank you for the report. Looks like a duplicate of https://github.com/ckeditor/ckeditor5/issues/11805, so let's track it in the main repo. Closing.

**Closed by FilipTokarski** 2022-05-23 08:48 UTC
