### ISSUE TITLE
ReOpening: https://github.com/ckeditor/ckeditor5-react/issues/375

### ISSUE THREAD

**Issue by shalapatil** [ckeditor/ckeditor5-react#384] opened 2023-06-05 05:37 UTC
Hello,
this is regarding my prev question: https://github.com/ckeditor/ckeditor5-react/issues/375
I am using custom build created by ckeditor team only
I have cloned https://github.com/ckeditor/strapi-plugin-ckeditor this and added my custom plugins there.
I have posted same question on that repo as well but not getting any response from there.

**Comment by martnpaneq** [comment] 2023-06-09 07:21
Hi @shalapatil.

Could you please provide us with a repository containing your code so we can reproduce the issue?

**Comment by corymharper** [comment] 2023-06-13 23:24
@martnpaneq I've just opened up #391 with a fairly detailed description and reproduction instructions.

**Comment by Witoso** [comment] 2023-06-16 06:45
@shalapatil we will handle your issue in the strapi repo (https://github.com/ckeditor/strapi-plugin-ckeditor/issues/64). And I will close this one.
@corymharper it looks like you commented on the wrong issue The link you posted is not related to this case.

**Closed by Witoso** 2023-06-16 06:45 UTC
