### ISSUE TITLE
CKEditor5 - How to set property at run time.

### ISSUE THREAD

**Issue by SKGGitHub** [ckeditor/ckeditor5-react#29] opened 2018-08-16 07:22 UTC
I want to make CKeditor5 readonly at runtime depending on condition. Although I got that there is a property "isReadOnly" to make CKEditor5 as read only but how to set this property at runtime, I got stuck something at. Is there any documentation which I can follow to achieve the same. FYI - I am integrating CKeditor5 source into my react application.

**Comment by Reinmar** [comment] 2018-08-16 07:50
You can change this property directly. It's not defined as "read-only" in [its documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#member-isReadOnly) which means that it can be modified from "outside", in this case, by an integration.

**Comment by Reinmar** [comment] 2018-08-16 07:55
Oopsie, I didn't notice that it's reported in ckeditor5-react. I thought it's a general question.

I'll reopen it and if you have further questions (like, how to access the `editor` instance in the runtime), then let us know.

**Comment by SKGGitHub** [comment] 2018-08-16 08:44
Thanks @Reinmar. Yes that would be helpful if it can be shared how to access editor at run time? Also, is it possible to configure editor with isReadOnly property at initialization itself with dynamic variable whose value will be changing during different phases of application and editor should react to that value everytime.

**Comment by SKGGitHub** [comment] 2018-08-16 09:50
I am able to achieve it. You can ignore it now. Thanks for your help.

**Comment by SKGGitHub** [comment] 2018-08-16 10:48
Yes sure..Below is the code I am using for it:

<CKEditor
                    editor={ClassicEditor}
                    data="<p>Hello...</p>"
                    onInit= {(editor) => this.state.editorHandle = editor}/>

   componentDidUpdate(){
        var editorHandle = this.state.editorHandle
        editorHandle.isReadOnly = this.props.isDisabled
    }

**Comment by SKGGitHub** [comment] 2018-08-16 10:50
Although it is working fine but one problem is here that we have ESLint and it is recommended that instead of using arrow functions u should use pure functions. So, while I try to replace it with pure function and passing editor as parameter to that it is going null, but if i use arrow function as it is in above comment, it is working fine. Any suggestion?

Below is the snipped for both oninit property one with arrow function and one with seperate function call.

<CKEditor
                    editor={ClassicEditor}
                    data="<p>Hello...</p>"
                    onInit= {(editor) => this.state.editorHandle = editor}/>
                    {/* onInit= {this.initialiseEditor(editor)}/> */}

**Comment by ma2ciek** [comment] 2018-08-16 11:06
> {/* onInit= {this.initialiseEditor(editor)}/> */}

This won't work, simply, because there's no `editor` variable available in that context and `this.initialiseEditor(editor)` is run at the Component bootstrap.

You need to pass here a function, not a function call. These are two different things.

E.g You can pass here:

`onInit={ this.initialiseEditor }`, which probably will make you trouble, because of the `this` inside the `initialiseEditor` method if the method is not bound to the component or use:
`onInit={ this.initialiseEditor.bind( this ) }`, which makes sure that the `initialiseEditor` method`s context will be correct.

Then you can have defined the `initialiseEditor` method, which will take the `editor` instance.
```
initialiseEditor( editor ) {

}
```
---
> componentDidUpdate(){
var editorHandle = this.state.editorHandle
editorHandle.isReadOnly = this.props.isDisabled
}

You should be aware, the editor (`this.state.editorHandle`) might not be available in this method if the call happens just after the editor component's bootstrap because the editor initialization is not synchronous.

**Comment by SKGGitHub** [comment] 2018-08-16 14:12
Thanks for increasing my knowledge in this
 context. So what should be the right way and which lifecycleethod should
be used to make it readonly baed on the property which i will get from
parent component

**Comment by ma2ciek** [comment] 2018-08-16 14:54
I'd just add an `if` statement to make sure that I'm operating on the `editor` that is not equal to `undefined`. i.e.:

```jsx
componentDidUpdate(){
	const editor = this.state.editor;

	if ( editor ) {
		editor.isReadOnly = this.props.isDisabled
	}
}
```

Perhaps it'd be good to add the `disabled` property to the React integration too as it's a common case and we have it in the Angular integration implemented already (https://github.com/ckeditor/ckeditor5-angular#disabled).
cc @pomek.

**Comment by SKGGitHub** [comment] 2018-08-17 03:28
Yes it worked like a charm. Thanks.

I appreciate the support you guys are providing that is very quick and kind support. THanks for all the help and I will keep on needing it as it is project for next 2 months and we use editor on very immense level. I hope you will be there to support.

**Comment by ma2ciek** [comment] 2018-08-17 08:15
We're happy to hear that :)

I'm closing it since the issue is answered already.

**Closed by ma2ciek** 2018-08-17 08:15 UTC
Labels: status:pending, type:question

**Comment by jailekkala** [comment] 2020-02-14 23:09
hi
