### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by vdhoangson** [ckeditor/ckeditor5-react#36] opened 2018-09-10 13:57 UTC
```
ReferenceError: window is not defined
    at Object.<anonymous> (/my_path/node_modules/@ckeditor/ckeditor5-react/dist/webpack:/CKEditor/webpack/universalModuleDefinition:10:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/son/Nodejs/dustgo/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/son/Nodejs/dustgo/client/modules/Blog/Post/pages/Admin/Edit.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/Users/son/Nodejs/dustgo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/son/Nodejs/dustgo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

How to fix it please?

**Comment by ma2ciek** [comment] 2018-09-10 14:29
Hi, @vdhoangson!

Could you describe some steps to reproduce the issue?

Thanks.

**Comment by vdhoangson** [comment] 2018-09-10 14:34
I have an article creation page

When I click the link to this page, it works fine

It only failed when I refreshed the page

**Comment by ma2ciek** [comment] 2018-09-10 14:45
Please, describe the setup, how you load the component, etc.

Without some details, it's impossible to reproduce it.

**Comment by vdhoangson** [comment] 2018-09-10 14:50
`import React, { Component } from 'react';
import { browserHistory, Link } from 'react-router';
import { connect } from 'react-redux';

import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

class CategoryAdd extends Component {
  constructor(props){
    super(props);
    this.state = {
      category: {
        title: '',
        description: '',
        parentId: '',
        status: 1,
        slug: '',
        feature: '',
        thumb: '',
      },
      categories: []
    };

  }
  componentDidMount() {

    this.initCategories();
  }
  componentWillReceiveProps(props){
    if(props.userInfo && props.userInfo.role !== 'admin') {
      browserHistory.push('/');
    }
    if(props.userInfo && props.userInfo.role === 'admin'){
      this.setState({ isAdmin: true });
    }
  }
  handleChangeItem = name => event => {
    var category = Object.assign({}, this.state.category);
    category[name] = event.target.value
    this.setState({
      category: category
    });
  }
  onChangeEditor(content) {
    let categoryInfo = this.state.category;
    categoryInfo.description = content;
    this.setState({
      category: categoryInfo
    });
  }
  initCategories(){
    getCategories({ status: 1 }).then(res => {
      if(res && res.data){
        this.setState({
          categories: res.data,
        });
      }
    });
  }
  render() {
    const categories = this.state.categories.map(
      category => <option value={category._id} key={category._id}>{category.title}</option>
    );

    const category = this.state.category;
    return (
      <div className="page-wrapper">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <div className="form-group">
                <FormattedMessage id="text_feature" />
                <img className="img-thumbnail" src={`/${category.thumb ? category.thumb : ''}`} />
                <input type="file" onChange={this.handleUploadFeature} />
              </div>
              <div className="form-group">
                <FormattedMessage id="text_title" />
                <input type="text" className="form-control" value={category.title} onChange={this.handleChangeItem('title')} />
                {this.state.warningTitle ? this.state.warningTitle : null }
              </div>
              <div className="form-group">
                <FormattedMessage id="text_description" />
                <CKEditor
                    editor={ ClassicEditor }
                    data="<p>Hello from CKEditor 5!</p>"
                    onInit={ editor => {
                        // You can store the "editor" and use when it's needed.
                        console.log( 'Editor is ready to use!', editor );
                    } }
                    onChange={ ( event, editor ) => {
                        const data = editor.getData();
                        console.log( { event, editor, data } );
                    } }
                />
              </div>
              <div className="form-group">
                <button type="button" onClick={this.handleAdd} className="btn btn-success"><FormattedMessage id="button_save" /></button>
                <Link to="admin/categories" className="btn btn-default"><FormattedMessage id="button_back" /></Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

// Retrieve data from store as props
function mapStateToProps(state) {
  return {
    userInfo: getUser(state),
  };
}
export default connect(mapStateToProps)(CategoryAdd);
`

**Comment by vdhoangson** [comment] 2018-09-10 14:52
[aaa.js.zip](https://github.com/ckeditor/ckeditor5-react/files/2367116/aaa.js.zip)
my file here

**Comment by vdhoangson** [comment] 2018-09-11 03:46
anyone help me?

**Comment by pomek** [comment] 2018-09-11 05:47
We ask you about steps to reproduce. You attached some file instead. What could we do with it? We need more details (e.g. webpack configuration, node & npm version, etc.).

Would be good if you create a repository with a minimal setup that allows reproducing the issue.

**Comment by vdhoangson** [comment] 2018-09-11 06:51
@pomek can you add my skype? 
skype: vdhoangson

**Comment by pomek** [comment] 2018-09-11 07:02
I guess you don't want to share with us your project. And I understand it. That's the reason why we're asking about steps and/or a minimal set-up for reproducing the issue.

We're asking because as you said:

> It only failed when I refreshed the page

That's weird and it does not sound like an error of CKEditor itself.

Answering your question - because you reported the issue here, we would like to help you here. If we resolve your problem, other developers could also resolve their issues in the future based on our messages.

**Comment by vdhoangson** [comment] 2018-09-11 07:10
I using mern stack http://mern.io/

https://github.com/Hashnode/mern-starter

And webpack config like this. Not edit anything

I was installed ckeditor-react base on document, it work when i click a tag to go to editor page, but when i refresh editor page, it show error

**Comment by pomek** [comment] 2018-09-11 07:15
Before I go deeper into the details of MERN, I would like to ask you about the last thing - which version of React do you use? You can check this in `node_modules/` or by typing `React.version` in the dev-tool console.

**Comment by vdhoangson** [comment] 2018-09-11 07:17
thanks @pomek 
now i'm using react v16.4.2

**Comment by pomek** [comment] 2018-09-19 07:10
The case described in the ticket is about missing `window` object when the component is rendering on the server (SSR). A very similar ticket is here https://github.com/ckeditor/ckeditor5-react/issues/31 so I'm closing this as a DUP.

**Closed by pomek** 2018-09-19 07:10 UTC
Labels: status:pending

**Comment by evenmed** [comment] 2019-10-18 01:22
I ran into this same issue when trying to use Next.js with Server-Side Rendering and CKEditor.

Here's how I fixed it in case it helps anyone:
```
import React form 'react';

class MyComponent extends React.Component {
    state = {isServer: true};
    
    componentDidMount() {
        // SSR doesn't fire ComponentDidMount, so we import CKEditor inside of it and store it as a component prop
        this.CKEditor = require("@ckeditor/ckeditor5-react");
        this.ClassicEditor = require("@ckeditor/ckeditor5-build-classic");
        this.setState({ isServer: false }); // We just do this to toggle a re-render
    }

    render() {
        return ({this.CKEditor && (<this.CKEditor editor={this.ClassicEditor} />)})
    }
}
```

**Comment by bipindubey-technoark** [comment] 2020-10-28 16:10
> I ran into this same issue when trying to use Next.js with Server-Side Rendering and CKEditor.
> 
> Here's how I fixed it in case it helps anyone:
> 
> ```
> import React form 'react';
> 
> class MyComponent extends React.Component {
>     state = {isServer: true};
>     
>     componentDidMount() {
>         // SSR doesn't fire ComponentDidMount, so we import CKEditor inside of it and store it as a component prop
>         this.CKEditor = require("@ckeditor/ckeditor5-react");
>         this.ClassicEditor = require("@ckeditor/ckeditor5-build-classic");
>         this.setState({ isServer: false }); // We just do this to toggle a re-render
>     }
> 
>     render() {
>         return ({this.CKEditor && (<this.CKEditor editor={this.ClassicEditor} />)})
>     }
> }
> ```

How to use this in functional component??

**Comment by RyanJeon** [comment] 2020-11-19 22:20
> > I ran into this same issue when trying to use Next.js with Server-Side Rendering and CKEditor.
> > Here's how I fixed it in case it helps anyone:
> > ```
> > import React form 'react';
> > 
> > class MyComponent extends React.Component {
> >     state = {isServer: true};
> >     
> >     componentDidMount() {
> >         // SSR doesn't fire ComponentDidMount, so we import CKEditor inside of it and store it as a component prop
> >         this.CKEditor = require("@ckeditor/ckeditor5-react");
> >         this.ClassicEditor = require("@ckeditor/ckeditor5-build-classic");
> >         this.setState({ isServer: false }); // We just do this to toggle a re-render
> >     }
> > 
> >     render() {
> >         return ({this.CKEditor && (<this.CKEditor editor={this.ClassicEditor} />)})
> >     }
> > }
> > ```
> 
> How to use this in functional component??

This worked for me using hooks

```
let CKEditor;
let ClassicEditor;

useEffect(() => {
  CKEditor = require("@ckeditor/ckeditor5-react");
  ClassicEditor = require("@ckeditor/ckeditor5-build-classic");
}, []);

```

**Comment by Max-Power-7** [comment] 2021-12-11 02:39
I have same problem in Next.js
¿Have solution?

**Comment by sleemkeen** [comment] 2022-06-01 10:05
https://stackoverflow.com/questions/66681320/how-ckeditor-5-works-at-next-js

**Comment by Bajrang179** [comment] 2022-11-25 05:18
I am getting the same issue with React version 18 (server side rendering). Can anyone help me with that.

**Comment by MathildeJolly** [comment] 2024-02-19 13:41
https://stackoverflow.com/questions/58447134/ckeditor-window-is-not-defined-reactjs-while-implementing/58576912#58576912
