### ISSUE TITLE
Icons floating outside toolbar

### ISSUE THREAD

**Issue by codeforsure** [ckeditor/ckeditor5-react#65] opened 2019-02-20 10:03 UTC
I was using custom build to render toolbar but my icons are floating outside toolbar 
this is my toolbar configuration
```
.ck-toolbar{
  min-height: 50px;
  width:inherit;
}
.ck-editor__editable {
    min-height: 300px;
}
```
```
<CKEditor
                    editor={ ClassicEditor }
                    data={this.state.content}
                    config={ {
                      toolbar:['heading','|',
                      'link','bulletedList','numberedList','alignment','imageUpload','blockQuote','insertTable','mediaEmbed','|','undo','redo','Underline', 'Strikethrough', 'Code', 'Subscript', 'Superscript', 'bold', 'italic', ],

                    } }
                    onChange={this.onChange}
                    onFocus={ editor => {
                        console.log( 'Focus.', editor );
                    } }
                />
```

<img width="1266" alt="screen shot 2019-02-20 at 3 35 08 pm" src="https://user-images.githubusercontent.com/25180754/53083556-2c038100-3525-11e9-8a78-1e48efcfc939.png">

**Comment by pomek** [comment] 2019-02-20 10:25
On the picture, I can't see too many details. It seems like some CSS collision occurred. You could debug it using browser dev-tools which are built-in.

I can't tell anything more if I am not enabled to reproduce the issue. Would be good to create some JSFiddle or prepare an instruction which describes step by step what we should do in order to reproduce the issue.

**Comment by codeforsure** [comment] 2019-02-20 10:39
I created a custom build with these plugins and importing this in my react project
```
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Code from '@ckeditor/ckeditor5-basic-styles/src/code';
import Subscript from '@ckeditor/ckeditor5-basic-styles/src/subscript';
import Superscript from '@ckeditor/ckeditor5-basic-styles/src/superscript';

import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';  

export default class ClassicEditor extends ClassicEditorBase {}

// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
	Essentials,
	UploadAdapter,
	Autoformat,
	Bold,
	Italic,
	BlockQuote,
	CKFinder,
	EasyImage,
	Heading,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Link,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	Alignment, Underline, Strikethrough, Code, Subscript, Superscript
];

// Editor configuration.
ClassicEditor.defaultConfig = {
	toolbar: {
		items: [
			'heading',
			'|',
			'bold',
			'italic','Underline', 'Strikethrough', 'Code', 'Subscript', 'Superscript',
			'alignment',
			'link',
			'bulletedList',
			'numberedList',
			'imageUpload',
			'blockQuote',
			'insertTable',
			'mediaEmbed',
			'undo',
			'redo'
		]
	},
	image: {
		toolbar: [
			'imageStyle:full',
			'imageStyle:side',
			'|',
			'imageTextAlternative'
		]
	},
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'en'
};

```
React Component
```
<div align='center' onSubmit ={this.onSubmit}>
      <form className= 'editor'>
      <h1 align='center'>Drop Your Complaints Here</h1>
      <CKEditor
                    editor={ ClassicEditor }
                    data={this.state.content}
                    onInit={editor => {
	       }}
                    config={ {
                    } }
                    onChange={this.onChange}
                    onFocus={ editor => {
                        console.log( 'Focus.', editor );
                    } }
                />
      <button  className="but1" type="submit" >{this.state.update ? <div>Update Complaint</div> :<div>Submit Complaint</div>}</button>
      </form>
      </div>
```
```
.editor{
  width:80%;
}
.ck-toolbar{
  min-height: 50px;
  width:inherit;
}
.ck-editor__editable {
    min-height: 300px;
}
```

**Comment by codeforsure** [comment] 2019-02-20 11:06
The same when done through html displays normal but when rendering with react the buttons are floating outside toolbar header

**Comment by pomek** [comment] 2019-02-20 11:30
I used your build, your component and your styles:

![image](https://user-images.githubusercontent.com/2270764/53088436-03ba5900-350a-11e9-8f49-94f8f5a67390.png)

Everything is looking good and working on. I hope you know that `align=center` is not the best method for centering the content. 

I'm closing this issue because it does not look like an error on our side.

**Closed by pomek** 2019-02-20 11:30 UTC
Labels: status:pending

**Comment by codeforsure** [comment] 2019-02-20 12:07
you checked in html page or in react component

**Comment by pomek** [comment] 2019-02-20 12:09
React Component.

**Comment by codeforsure** [comment] 2019-02-20 12:14
Thank you for your time I have found out the issue its because of css collision of buttons

**Comment by codeforsure** [comment] 2019-02-21 11:52
hi @pomek 
```
.ck-editor__editable {
    min-height: 300px;
}
```
I have using this to resize the editor area but when I upload the image the caption area is also resizing to 300px.
Is the same class name is used for both??
