### ISSUE TITLE
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-react'

### ISSUE THREAD

**Issue by GeoDaz** [ckeditor/ckeditor5-react#303] opened 2022-04-28 07:09 UTC
Hello, this could looks like a duplicated issue, but the result is not the same, I think.
I launch a create react app, to test this, version 5.0.1, node version 16.13.2, OS windows 10 x64.
I follow the documentation : 
`npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic`
And node_modules/@ckeditor/ckeditor5-react/, just contains : 
LICENCE.md, package.json and README.md
So when I `import { CKEditor, CKEditorContext } from '@ckeditor/ckeditor5-react';`. 
Result : the module is not found.

I had to change this : 
```js
import Context from '@ckeditor/ckeditor5-core/src/context';
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
```
to this : 
```js
import { Context } from '@ckeditor/ckeditor5-core';
import { ClassicEditor } from '@ckeditor/ckeditor5-editor-classic';
import { Bold, Italic } from '@ckeditor/ckeditor5-basic-styles';
import { Essentials } from '@ckeditor/ckeditor5-essentials';
import { Paragraph } from '@ckeditor/ckeditor5-paragraph';
```

**Comment by pomek** [comment] 2022-05-27 09:23
Hi, @GeoDaz,

Do you resolve your problem? If not, please, share more details on how to reproduce the issue. It will help us understand the problem.

**Comment by hemeda3** [comment] 2022-05-27 22:51
I have exactly the same issue

**Comment by pomek** [comment] 2022-06-24 09:11
Closing due to lack of required steps for reproducing the problem.

**Closed by pomek** 2022-06-24 09:11 UTC
Labels: pending:feedback
