### ISSUE TITLE
Build Error showing ( Works fine in Dev version ) in NextJs

### ISSUE THREAD

**Issue by RetiFier** [ckeditor/ckeditor5-react#191] opened 2020-10-15 14:59 UTC
The problem is when we try to run build mode of Next JS which includes CK Editor, it shows the following error.
> Build error occurred ReferenceError: window is not defined at Object.<anonymous> (D:\Project\Reallyy\reallyy-client\node_modules\@ckeditor\ckeditor5-react\dist\ckeditor.js:5:244)

This error doesn't exist in development version. It works all the fine in our development server but once we try to build it, things go nasty this way. Couldn't figure out a way to solve yet. Thanks in advance. :))

**Comment by FilipTokarski** [comment] 2020-10-16 12:26
Hi, the error is caused by server side rendering in Next. Unfortunately CKEditor does not work out-of-the box in such frameworks. Please check the workaround mentioned [here](https://github.com/ckeditor/ckeditor5-react/issues/36#issuecomment-543438569). I'll close this ticket for now as this is generally a duplicate of [this issue](https://github.com/ckeditor/ckeditor5/issues/1511).

**Closed by FilipTokarski** 2020-10-16 12:26 UTC

**Comment by riteshsingh1** [comment] 2023-05-31 03:28
In nextjs 13, you can use - 
`export const dynamic = "force-dynamic";`

and it will work fine.
