### ISSUE TITLE
Heading styles are inconsistent in ckeditor's own editor vs headings pasted from google docs however, for ms word it is consistent. N eed quick resolution

### ISSUE THREAD

**Issue by tista-chatterjee** [ckeditor/ckeditor5-react#286] opened 2022-02-25 08:10 UTC
<img width="767" alt="ckeditor heading" src="https://user-images.githubusercontent.com/91665085/155679017-5df8cf1a-768f-4464-863f-24108e636cb2.png">
See image:

Bold H1 test - content that has been typed directly into CKEditor (H1).

Non-bold 'Google Docs - Test Content for UAT' - content that has been pasted from Google Docs, then an H1 tag applied to the words.

Expectation would be that all content displays the same:

**Comment by FilipTokarski** [comment] 2022-03-10 08:40
Duplicate of https://github.com/ckeditor/ckeditor5/issues/11339.

**Closed by FilipTokarski** 2022-03-10 08:40 UTC
